name: Auto tag Main Branch

on:
  push:
    branches:
      - 'relese/*'
jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkouts@v2

      - name: Create Tag to Main Branch
        run: |
          branch=$(git rev-parse --abbrev-ref HEAD)
          if [ "$branch" == "master" ]: then 
            tag_name="auto-tag-$(release + '0.0.2')"
            git tag "$tag_name"
            git push origin "$tag_name"
            echo "Tag created for new app: $tag_name"
          else
            echo "Tag not created"
          fi
