name: Auto tag Main Branch

on:
  push:
    branches:
      - 'release/*'
jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Create Tag to Main Branch
        run: |
          branch=$(git for-each-ref --format="%(upstream:short)" $(git symbolic-ref -q HEAD))
          echo "This is the branch head: $branch"
          echo "this is head: $HEAD"
          # rutina para splitear la version que se puso en la brnacha
          IFS="/" read -ra version_array <<< "$branch"
          version_number="${{ version_array[2] }}"
          echo "version number: $version_number"
          if [[ $branch == *"release"* ]]; then 
            tag_name="auto-release-tag-v$version_number"
            echo "this is the tag: $tag_name"
            git tag "$tag_name"
            git push origin "$tag_name"
            echo "Tag created for new app: $tag_name"
          else
            echo "Tag not created"
          fi
