name: Update minor version

on:
  pull_request:
      types:
        - opened
jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Bump version of pr
        run: |
          cd PrintApp
          
          current_version=$(grep "versionName" app/build.gradle | sed -n 's/.*versionName "\(.*\)".*/\1/p')
          echo "Version extraida : $current_version"

          # rutina para splitear el minor 
          IFS="." read -ra version_name_items <<< "$current_version"
          #major="${version_name_items[0]}"
          #minor="${version_name_items[1]}"
          patch=${version_name_items[2]}"

          # rutina para sobreescribir 
          version_minor=$((((patch)) + 1))
          version_name="${major}.${version_minor}.${patch}"
          
          echo "esta es la v $version_name"

          sed -i "s/versionName \"[0-9.]\+\"/versionName \"$version_name\"/" app/build.gradle
          
          # commit changes
          git config user.email "mail@rccl.com"
          git config user.name "RCCL-automated versioning"
          git add app/build.gradle
          git commit -m "Application version updated to $version_name"
          git push origin
