name: Update minor version

on:
  pull_request:
    types:
      - opened
jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Bump version of pr
        run: |
          cd PrintApp
          
          current_version=$(grep "versionName" app/build.gradle | sed -n 's/.*versionName "\(.*\)".*/\1/p')
          echo "Version extraida $current_version"

          # rutina para splitear el minor 
          IFS="." read -ra version_name_items <<< "$current_version"
          #major="${version_name_items[0]}"
          #minor="${version_name_items[1]}"
          patch=${version_name_items[2]}"

          echo "este es patch $patch"
